image: node:latest

stages:
  - test
  - build


test:
    stage: test
    
    cache:
      paths:
        - app/node_modules/
    
    before_script:
        - unset CI
        - cd app
        - npm install npm@latest -g
    
    script:
        - npm install
        - npm run testAll
        - npm run coverage
    
    coverage: /All\sfiles.*?\s+(\d+.\d+)/


build:
    image: docker:19.03.1
    stage: build

    variables:
        DOCKER_TLS_CERTDIR: "/certs"

    services:
        - docker:19.03.1-dind

    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    script:
        - docker build -t $CI_REGISTRY/hmerritt/internet-checker:latest .
        - docker push $CI_REGISTRY/hmerritt/internet-checker:latest
        
    only:
        - master
