language: generic

services:
  - docker
 
before_script:
  - docker build -t hmerritt/internet-checker -f Dockerfile .

script:
  - docker run hmerritt/internet-checker npm run coverage

deploy:
  provider: script
  script:
    - docker login -u DOCKER_USER -p DOCKER_PASS
    - docker push hmerritt/internet-checker:latest
  on:
    branch: master