jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "stable"
      cache:
        directories:
          - "app/node_modules"
      before_script:
        - unset CI
        - cd app
      script:
        - npm install
        - npm run coverage
        - npm run build

    - stage: deploy
      language: generic
      if: type = push AND branch = master
      services:
        - docker
      before_script:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      script:
        - docker build -t hmerritt/internet-checker -f Dockerfile .
        - docker push hmerritt/internet-checker:latest

notifications:
    email: false